version: "3"
services:
  app:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - app-network
    command: python app.py

networks:
  app-network:
